version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: elearning-postgres
    restart: always
    environment:
      POSTGRES_USER: elearning_user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elearning
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elearning-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://elearning_user:postgres@postgres:5432/elearning
    ports:
      - "8080:8000"
    volumes:
      - .:/workspace
      - /workspace/venv
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: elearning-frontend
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_USE_POLLING=true
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data: