"""add_question_type_to_quizzes

Revision ID: 3a3c96215ccc
Revises: 2471d49ce377
Create Date: 2026-07-13 12:16:58.348817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a3c96215ccc'
down_revision: Union[str, Sequence[str], None] = '2471d49ce377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('question_type', sa.String(), server_default='mcq', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_questions', 'question_type')
    # ### end Alembic commands ###
