"""add progress_percent to course_enrollments

Revision ID: 3ad91bd45fc4
Revises: 416156a8f3cf
Create Date: 2026-06-29 14:57:53.808552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad91bd45fc4'
down_revision: Union[str, Sequence[str], None] = '416156a8f3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_enrollments', sa.Column('progress_percent', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_enrollments', 'progress_percent')
    # ### end Alembic commands ###
