"""add_duration_and_priority_to_courses

Revision ID: 416156a8f3cf
Revises: 068da708842c
Create Date: 2026-06-29 12:01:29.848964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '416156a8f3cf'
down_revision: Union[str, Sequence[str], None] = '068da708842c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('priority', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'priority')
    op.drop_column('courses', 'duration')
    # ### end Alembic commands ###
