"""add_badge_tiers_and_update_user_badges

Revision ID: 5629644799d0
Revises: d20000000001
Create Date: 2026-07-22 09:29:05.838186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5629644799d0'
down_revision: Union[str, Sequence[str], None] = 'd20000000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge_tiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tier_order', sa.Integer(), nullable=False),
    sa.Column('icon_asset_ref', sa.String(), nullable=False),
    sa.Column('courses_required_cumulative', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('tier_order')
    )
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_course_enrollments_course_id'), table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_user_id'), table_name='course_enrollments')
    op.drop_index(op.f('ix_courses_created_by'), table_name='courses')
    op.drop_index(op.f('ix_courses_department_id'), table_name='courses')
    op.drop_index(op.f('ix_exam_assignments_department_id'), table_name='exam_assignments')
    op.drop_index(op.f('ix_exam_assignments_exam_id'), table_name='exam_assignments')
    op.drop_index(op.f('ix_exam_submissions_exam_id'), table_name='exam_submissions')
    op.drop_index(op.f('ix_exam_submissions_user_id'), table_name='exam_submissions')
    op.drop_index(op.f('ix_exams_course_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_department_id'), table_name='exams')
    op.add_column('user_badges', sa.Column('badge_tier_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'user_badges', 'badge_tiers', ['badge_tier_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_badges', 'badge_name')
    op.drop_column('user_badges', 'step')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.add_column('user_badges', sa.Column('step', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_badges', sa.Column('badge_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_badges', type_='foreignkey')
    op.drop_column('user_badges', 'badge_tier_id')
    op.create_index(op.f('ix_exams_department_id'), 'exams', ['department_id'], unique=False)
    op.create_index(op.f('ix_exams_course_id'), 'exams', ['course_id'], unique=False)
    op.create_index(op.f('ix_exam_submissions_user_id'), 'exam_submissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_exam_submissions_exam_id'), 'exam_submissions', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_assignments_exam_id'), 'exam_assignments', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_assignments_department_id'), 'exam_assignments', ['department_id'], unique=False)
    op.create_index(op.f('ix_courses_department_id'), 'courses', ['department_id'], unique=False)
    op.create_index(op.f('ix_courses_created_by'), 'courses', ['created_by'], unique=False)
    op.create_index(op.f('ix_course_enrollments_user_id'), 'course_enrollments', ['user_id'], unique=False)
    op.create_index(op.f('ix_course_enrollments_course_id'), 'course_enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.drop_table('badge_tiers')
    # ### end Alembic commands ###
