"""add_tier_published_at_and_mandatory

Revision ID: a280c8373256
Revises: e3116af5559a
Create Date: 2026-07-10 10:58:37.244269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a280c8373256'
down_revision: Union[str, Sequence[str], None] = 'e3116af5559a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_modules', sa.Column('tier', sa.String(), server_default='beginner', nullable=False))
    op.add_column('courses', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('courses', sa.Column('is_mandatory', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'is_mandatory')
    op.drop_column('courses', 'published_at')
    op.drop_column('course_modules', 'tier')
    # ### end Alembic commands ###
