"""create authentication schema

Revision ID: cd4ec1a6712e
Revises: 
Create Date: 2026-06-20 15:59:13.561616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4ec1a6712e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_code'), 'users', ['employee_code'], unique=True)
    op.create_table('password_reset_otps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # --- Database Seeding ---
    # Define table structures for inserting
    roles_table = sa.table('roles',
        sa.column('id', sa.UUID()),
        sa.column('name', sa.String()),
    )
    users_table = sa.table('users',
        sa.column('id', sa.UUID()),
        sa.column('employee_code', sa.String()),
        sa.column('first_name', sa.String()),
        sa.column('last_name', sa.String()),
        sa.column('email', sa.String()),
        sa.column('password_hash', sa.String()),
        sa.column('is_active', sa.Boolean()),
        sa.column('is_deleted', sa.Boolean()),
        sa.column('must_change_password', sa.Boolean()),
    )
    user_roles_table = sa.table('user_roles',
        sa.column('id', sa.UUID()),
        sa.column('user_id', sa.UUID()),
        sa.column('role_id', sa.UUID()),
    )

    # 1. Seed Roles
    admin_role_id = "a0a0a0a0-0000-0000-0000-000000000001"
    manager_role_id = "a0a0a0a0-0000-0000-0000-000000000002"
    employee_role_id = "a0a0a0a0-0000-0000-0000-000000000003"
    op.bulk_insert(roles_table, [
        {'id': admin_role_id, 'name': 'ADMIN'},
        {'id': manager_role_id, 'name': 'MANAGER'},
        {'id': employee_role_id, 'name': 'EMPLOYEE'}
    ])

    # 2. Seed Users
    emp_user_id = "11111111-1111-1111-1111-111111111111"
    admin_user_id = "22222222-2222-2222-2222-222222222222"
    op.bulk_insert(users_table, [
        {
            'id': emp_user_id,
            'employee_code': 'EMP001',
            'first_name': 'John',
            'last_name': 'Doe',
            'email': 'john.doe@lms.com',
            'password_hash': '$2b$12$6OaFdsPMOHA9GLZ4v7PptOl917FhIivrPjLb0nYqQN2tXDvIz7Dnm',
            'is_active': True,
            'is_deleted': False,
            'must_change_password': True
        },
        {
            'id': admin_user_id,
            'employee_code': 'ADM001',
            'first_name': 'Admin',
            'last_name': 'User',
            'email': 'admin@lms.com',
            'password_hash': '$2b$12$6OaFdsPMOHA9GLZ4v7PptOl917FhIivrPjLb0nYqQN2tXDvIz7Dnm',
            'is_active': True,
            'is_deleted': False,
            'must_change_password': True
        }
    ])

    # 3. Seed User Roles Mapping
    op.bulk_insert(user_roles_table, [
        {
            'id': "33333333-3333-3333-3333-333333333333",
            'user_id': emp_user_id,
            'role_id': employee_role_id
        },
        {
            'id': "44444444-4444-4444-4444-444444444444",
            'user_id': admin_user_id,
            'role_id': admin_role_id
        }
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('password_reset_otps')
    op.drop_index(op.f('ix_users_employee_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
